---
# defaults file for docker_install


# Servizio docker 
docker_service: docker

# Repo RH family vars
repo_baseurl_rh_family: https://download.docker.com/linux/{{ ansible_distribution | lower }}/$releasever/$basearch/stable
repo_name_rh_family: docker-ce-stable
repo_file_rh_family: docker-ce
repo_desc_rh_family: Docker CE Stable - $basearch
repo_gpk_rh_family: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

# Pacchetti da rimuovere per installazione pulita
docker_packages_remove_rh:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-engine
  - docker-selinux
  - docker-engine-selinux

docker_allow_downgrade: true

# Repo Debian family vars
repo_baseurl_debian_family: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }}   {{ ansible_distribution_release }}  stable 

# Pacchetti da installare 
docker_packages_install:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin
  - docker-buildx-plugin

# Disco da utilizzare per montare cartella var/lib
disk_device: /dev/sdc #dev/sda2