#task for install apache2

- name: Install Apache (RedHat or Fedora)
  package:
    name: "{{ pkg_name_rh }}"
    state: present
  when: ansible_facts['distribution'] in ['Fedora', 'CentOS']

- name: Install Apache (Debian or Ubuntu)
  package:
    name: "{{ pkg_name_debian }}"
    state: present
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']

- name: Scarica la blacklist
  get_url:
    url: https://myip.ms/files/blacklist/general/latest_blacklist.txt
    dest: /var/www/html/latest_blacklist.txt
  register: blacklist

- debug:
    msg: 
      - " blacklist ---"
      - " {{ blacklist }}"

- when: blacklist.changed
  name: Delete old blacklist
  file: 
    path: "{{ configuration_path }}/10-blacklist.conf"
    state: absent

# - when: blacklist.changed or true
#   name: Parsing della blacklist e aggiunta alla configurazione di Apache
#   lineinfile:
#     create: true
#     path: "{{ configuration_path }}/10-blacklist.conf"
#     line: "Deny from {{ item }}"
#   loop: "{{ lookup('file', '/var/www/html/latest_blacklist.txt').split('\n') }}"
#   notify: Riavvia Apache
#when: item | regex_search('^\\d+\\.\\d+\\.\\d+\\.\\d+')

- name: Crea una pagina web personalizzata con un link alla blacklist
  copy:
    dest: /var/www/html/index.html
    content: |
      <h1>Benvenuto!</h1>
      <p><a href="/latest_blacklist.txt">Clicca qui per vedere la blacklist</a></p>

- name: Configura Apache VirtualHost
  blockinfile:
    path: /etc/apache2/sites-available/000-default.conf
    block: |
      <VirtualHost *:80>
        DocumentRoot /var/www/html
        <Directory /var/www/html>
          Options Indexes FollowSymLinks
          AllowOverride None
          Require all granted
        </Directory>
      </VirtualHost>
  notify: Riavvia Apache

  