#task for install apache2

- name: Install Apache
  package:
    name: "{{ pkg_name }}"
    state: present

- name: Scaricamento blacklist
  uri:
    url: "{{ blacklist_url }}"
    return_content: true
  register: blacklist

- name: Aggiunta blacklist alla configurazione Apache
  template:
    src: denylist.j2
    dest: "{{ configuration_file_path }}"
  notify: Riavvia Apache

- name: Creazione pagina web
  copy:
    dest: "{{ html_file }}"
    content: "{{ html_content }}"
