
# Aggiunta repo per sistemi Debian
- name: Add Docker repository for Debian
  apt_repository:
    repo: "{{repo_baseurl_debian_family}}"
    state: present

# Installa pacchetti necessari
- name: Installa/Aggiorna i pacchetti Docker
  apt:
    name: "{{ item }}"
    state: latest
    allow_downgrade: "{{ docker_allow_downgrade }}"
  loop: "{{ docker_packages_inst_ubuntu }}"






