---
# task file main

- name: Montaggio disco in/var/lib/docker
  include_tasks: add_docker_disk.yml
  when: ('/var/lib/docker' not in ansible_mounts | map(attribute='mount')) | bool

- name: install for RH
  include_tasks: redhat_install.yml
  when: (ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_major_version'] >= "38") or (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] >= "7")

- name: install for debian
  include_tasks: debian_install.yml
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version']  >= "20")

- name: Start Docker service
  service:
    name: "{{ docker_service }}"
    state: started 
