---
# tasks file for docker_install

# - name: Controlla se Docker è già installato
#   package:
#     name: "{{ docker_package }}"
#     state: present
#   register: docker_installed

# - name: Disinstalla Docker se presente
#   package:
#     name: "{{ docker_package }}"
#     state: absent
#   when: docker_installed is changed

# - name: Installa Docker
#   package:
#     name: "{{ docker_package }}"
#     state: present


- name: Gather facts about installed packages
  package_facts:

- name: Check if Docker is installed
  set_fact:
    docker_installed: "{{ 'docker-ce' in ansible_facts.packages | default([]) }}"

- name: Stop Docker service
  systemd:
    name: "{{ docker_service }}"
    state: stopped
  when: docker_installed

- name: Uninstall Docker
  package:
    name: "{{ docker_package }}"
    state: absent
  when: docker_installed

- name: Install Docker
  package:
    name: "{{ docker_package }}"
    state: present
  when: not docker_installed

- name: Start Docker service
  systemd:
    name: "{{ docker_service }}"
    state: started
  when: not docker_installed

- name: Print Docker install status  
  debug:
    msg: "Docker is installed: {{ docker_installed }}"
