- name: Installazione docker
  hosts: fe
  connection: local
  become: true
  tasks:
    
    - name: includi role per installazione di docker
      include_role: 
        name: docker_install
      
    # - name: restart docker service   handlress
    #   notify: restart docker


